"""Chinese -> English country name translation for dashboard display.

Mapping covers the ~150 most common markets seen in mobile recharge data.
If a country name is not in the dict, the original value is returned
unchanged (so untranslated entries are still visible, just in their
source language).

Usage:
    from country_mapping import translate_country
    df['country'] = df['country'].map(translate_country)
"""

CN_TO_EN = {
    # East Asia
    "中国": "China",
    "中国大陆": "China",
    "中国香港": "Hong Kong",
    "香港": "Hong Kong",
    "中国澳门": "Macao",
    "澳门": "Macao",
    "中国台湾": "Taiwan",
    "台湾": "Taiwan",
    "日本": "Japan",
    "韩国": "South Korea",
    "大韩民国": "South Korea",
    "南韩": "South Korea",
    "朝鲜": "North Korea",
    "蒙古": "Mongolia",
    "蒙古国": "Mongolia",
    # Southeast Asia
    "马来西亚": "Malaysia",
    "印度尼西亚": "Indonesia",
    "印度尼西亚(印尼)": "Indonesia",
    "印尼": "Indonesia",
    "菲律宾": "Philippines",
    "新加坡": "Singapore",
    "泰国": "Thailand",
    "越南": "Vietnam",
    "缅甸": "Myanmar",
    "柬埔寨": "Cambodia",
    "老挝": "Laos",
    "文莱": "Brunei",
    "东帝汶": "Timor-Leste",
    # South Asia
    "印度": "India",
    "巴基斯坦": "Pakistan",
    "孟加拉国": "Bangladesh",
    "孟加拉": "Bangladesh",
    "斯里兰卡": "Sri Lanka",
    "尼泊尔": "Nepal",
    "不丹": "Bhutan",
    "马尔代夫": "Maldives",
    "阿富汗": "Afghanistan",
    # Central Asia
    "哈萨克斯坦": "Kazakhstan",
    "乌兹别克斯坦": "Uzbekistan",
    "塔吉克斯坦": "Tajikistan",
    "吉尔吉斯斯坦": "Kyrgyzstan",
    "土库曼斯坦": "Turkmenistan",
    # Middle East
    "沙特阿拉伯": "Saudi Arabia",
    "沙特": "Saudi Arabia",
    "阿联酋": "United Arab Emirates",
    "阿拉伯联合酋长国": "United Arab Emirates",
    "卡塔尔": "Qatar",
    "科威特": "Kuwait",
    "巴林": "Bahrain",
    "阿曼": "Oman",
    "也门": "Yemen",
    "伊朗": "Iran",
    "伊拉克": "Iraq",
    "叙利亚": "Syria",
    "约旦": "Jordan",
    "黎巴嫩": "Lebanon",
    "以色列": "Israel",
    "巴勒斯坦": "Palestine",
    "土耳其": "Turkey",
    # Africa
    "埃及": "Egypt",
    "利比亚": "Libya",
    "苏丹": "Sudan",
    "南苏丹": "South Sudan",
    "摩洛哥": "Morocco",
    "阿尔及利亚": "Algeria",
    "突尼斯": "Tunisia",
    "南非": "South Africa",
    "尼日利亚": "Nigeria",
    "肯尼亚": "Kenya",
    "埃塞俄比亚": "Ethiopia",
    "坦桑尼亚": "Tanzania",
    "乌干达": "Uganda",
    "加纳": "Ghana",
    "塞内加尔": "Senegal",
    "象牙海岸": "Côte d'Ivoire",
    "科特迪瓦": "Côte d'Ivoire",
    "喀麦隆": "Cameroon",
    "津巴布韦": "Zimbabwe",
    "赞比亚": "Zambia",
    "博茨瓦纳": "Botswana",
    "莫桑比克": "Mozambique",
    "安哥拉": "Angola",
    "卢旺达": "Rwanda",
    "布隆迪": "Burundi",
    "索马里": "Somalia",
    "吉布提": "Djibouti",
    "厄立特里亚": "Eritrea",
    "马达加斯加": "Madagascar",
    "毛里求斯": "Mauritius",
    "塞舌尔": "Seychelles",
    "科摩罗": "Comoros",
    "冈比亚": "Gambia",
    "几内亚": "Guinea",
    "几内亚比绍": "Guinea-Bissau",
    "塞拉利昂": "Sierra Leone",
    "利比里亚": "Liberia",
    "马里": "Mali",
    "布基纳法索": "Burkina Faso",
    "尼日尔": "Niger",
    "乍得": "Chad",
    "中非共和国": "Central African Republic",
    "刚果共和国": "Republic of the Congo",
    "刚果(布)": "Republic of the Congo",
    "刚果民主共和国": "Democratic Republic of the Congo",
    "刚果(金)": "Democratic Republic of the Congo",
    "刚果金": "Democratic Republic of the Congo",
    "加蓬": "Gabon",
    "赤道几内亚": "Equatorial Guinea",
    "圣多美和普林西比": "São Tomé and Príncipe",
    "莱索托": "Lesotho",
    "斯威士兰": "Eswatini",
    "埃斯瓦蒂尼": "Eswatini",
    "纳米比亚": "Namibia",
    "毛里塔尼亚": "Mauritania",
    "贝宁": "Benin",
    "多哥": "Togo",
    "佛得角": "Cape Verde",
    "马拉维": "Malawi",
    # Europe
    "英国": "United Kingdom",
    "法国": "France",
    "德国": "Germany",
    "意大利": "Italy",
    "西班牙": "Spain",
    "葡萄牙": "Portugal",
    "荷兰": "Netherlands",
    "比利时": "Belgium",
    "卢森堡": "Luxembourg",
    "瑞士": "Switzerland",
    "奥地利": "Austria",
    "丹麦": "Denmark",
    "瑞典": "Sweden",
    "挪威": "Norway",
    "芬兰": "Finland",
    "冰岛": "Iceland",
    "爱尔兰": "Ireland",
    "波兰": "Poland",
    "捷克": "Czechia",
    "斯洛伐克": "Slovakia",
    "匈牙利": "Hungary",
    "罗马尼亚": "Romania",
    "保加利亚": "Bulgaria",
    "希腊": "Greece",
    "塞尔维亚": "Serbia",
    "克罗地亚": "Croatia",
    "斯洛文尼亚": "Slovenia",
    "波黑": "Bosnia and Herzegovina",
    "波斯尼亚和黑塞哥维那": "Bosnia and Herzegovina",
    "黑山": "Montenegro",
    "北马其顿": "North Macedonia",
    "马其顿": "North Macedonia",
    "阿尔巴尼亚": "Albania",
    "俄罗斯": "Russia",
    "乌克兰": "Ukraine",
    "白俄罗斯": "Belarus",
    "摩尔多瓦": "Moldova",
    "立陶宛": "Lithuania",
    "拉脱维亚": "Latvia",
    "爱沙尼亚": "Estonia",
    "格鲁吉亚": "Georgia",
    "亚美尼亚": "Armenia",
    "阿塞拜疆": "Azerbaijan",
    "塞浦路斯": "Cyprus",
    "马耳他": "Malta",
    "摩纳哥": "Monaco",
    "安道尔": "Andorra",
    "列支敦士登": "Liechtenstein",
    "圣马力诺": "San Marino",
    "梵蒂冈": "Vatican City",
    # Americas
    "美国": "United States",
    "加拿大": "Canada",
    "墨西哥": "Mexico",
    "危地马拉": "Guatemala",
    "伯利兹": "Belize",
    "洪都拉斯": "Honduras",
    "萨尔瓦多": "El Salvador",
    "尼加拉瓜": "Nicaragua",
    "哥斯达黎加": "Costa Rica",
    "巴拿马": "Panama",
    "古巴": "Cuba",
    "牙买加": "Jamaica",
    "海地": "Haiti",
    "多米尼加共和国": "Dominican Republic",
    "多米尼加": "Dominican Republic",
    "波多黎各": "Puerto Rico",
    "特立尼达和多巴哥": "Trinidad and Tobago",
    "巴巴多斯": "Barbados",
    "巴哈马": "Bahamas",
    "多米尼克": "Dominica",
    "库拉索": "Curaçao",
    "格林纳达": "Grenada",
    "百慕大": "Bermuda",
    "安提瓜和巴布达": "Antigua and Barbuda",
    "留尼旺": "Réunion",
    "巴西": "Brazil",
    "阿根廷": "Argentina",
    "智利": "Chile",
    "秘鲁": "Peru",
    "哥伦比亚": "Colombia",
    "委内瑞拉": "Venezuela",
    "厄瓜多尔": "Ecuador",
    "玻利维亚": "Bolivia",
    "巴拉圭": "Paraguay",
    "乌拉圭": "Uruguay",
    "苏里南": "Suriname",
    "圭亚那": "Guyana",
    "法属圭亚那": "French Guiana",
    # Oceania
    "澳大利亚": "Australia",
    "澳洲": "Australia",
    "新西兰": "New Zealand",
    "巴布亚新几内亚": "Papua New Guinea",
    "斐济": "Fiji",
    "汤加": "Tonga",
    "萨摩亚": "Samoa",
    "瓦努阿图": "Vanuatu",
    "所罗门群岛": "Solomon Islands",
    "基里巴斯": "Kiribati",
    "图瓦卢": "Tuvalu",
    "瑙鲁": "Nauru",
    "帕劳": "Palau",
    "密克罗尼西亚": "Micronesia",
    "马绍尔群岛": "Marshall Islands",
    # Catch-all / common variants
    "未知": "Unknown",
    "其他": "Other",
}


def translate_country(value):
    """Return the English country name if known, else the original value."""
    if value is None:
        return value
    s = str(value).strip()
    if not s:
        return value
    return CN_TO_EN.get(s, value)
